CREATE OR 
REPLACE VIEW PSFT.PSPMTRANS11_VW 
	(
		PM_INSTANCE_ID, PM_TRANS_DEFN_SET, PM_TRANS_DEFN_ID, PM_AGENTID, OPRID, 
		PM_PERF_TRACE, PM_CONTEXT_VALUE1, PM_CONTEXT_VALUE2, PM_CONTEXT_VALUE3, 
		PM_AGENT_STRT_DTTM, PM_MON_STRT_DTTM, PM_TRANS_DURATION, 
		PM_PARENT_INST_ID, PM_TOP_INST_ID, PM_METRIC_VALUE1, PM_METRIC_VALUE2, 
		PM_METRIC_VALUE3, PM_METRIC_VALUE4, PM_METRIC_VALUE5, PM_METRIC_VALUE6, 
		PM_METRIC_VALUE7, PM_CHART_XAXIS, PM_CHART_SERIES, PM_CHART_HINTS, 
		PM_CHART_COLOR, PM_CHART_YAXIS, PM_CHART_POS, PM_ADDTNL_DESCR 
	)
	AS 
SELECT C.PM_INSTANCE_ID , C.PM_TRANS_DEFN_SET , C.PM_TRANS_DEFN_ID , C.
	PM_AGENTID , C.OPRID , C.PM_PERF_TRACE , C.PM_CONTEXT_VALUE1 , C.
	PM_CONTEXT_VALUE2 , C.PM_CONTEXT_VALUE3 , C.PM_AGENT_STRT_DTTM , C.
	PM_MON_STRT_DTTM , C.PM_TRANS_DURATION , C.PM_PARENT_INST_ID , C.
	PM_TOP_INST_ID , C.PM_METRIC_VALUE1 , C.PM_METRIC_VALUE2 , C.
	PM_METRIC_VALUE3 , C.PM_METRIC_VALUE4 , C.PM_METRIC_VALUE5 , C.
	PM_METRIC_VALUE6 , C.PM_METRIC_VALUE7 , ' ' , ' ' , ' ' , 0 , 0 , 0 , C.
	PM_ADDTNL_DESCR 
FROM PSPMTRANSHIST C 
WHERE C.PM_TRANS_DEFN_SET = 1 AND C.PM_TRANS_DEFN_ID = 401
/
