CREATE TABLE PSFT.AA_TOP_DURATION  ( 
    TRANSDATE        	DATE NULL,
    AVERAGE          	NUMBER NULL,
    WEIGHTED         	NUMBER NULL,
    COUNTER          	NUMBER NULL,
    PM_CONTEXT_VALUE1	VARCHAR2(762) NOT NULL,
    PM_CONTEXT_VALUE2	VARCHAR2(762) NOT NULL,
    PM_CONTEXT_VALUE3	VARCHAR2(762) NOT NULL 
    )
TABLESPACE PSDEFAULT PCTFREE 10 INITRANS 1 MAXTRANS 255 
STORAGE( INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 )
NOPARALLEL
LOGGING 
NOCACHE 
NOMONITORING 
NOROWDEPENDENCIES
DISABLE ROW MOVEMENT 
/

--------------------------------------

CREATE TABLE PSFT.STAT_TRANSHIST_AVG  ( 
    COLLECT_DATE     	DATE NULL,
    PM_CONTEXT_VALUE1	VARCHAR2(762) NOT NULL,
    PM_CONTEXT_VALUE2	VARCHAR2(762) NOT NULL,
    PM_CONTEXT_VALUE3	VARCHAR2(762) NOT NULL,
    AVERAGE          	NUMBER NULL,
    STD_DEV          	NUMBER NULL,
    COUNTER          	NUMBER NULL,
    SYNCDTTM         	DATE NULL 
    )
TABLESPACE PSDEFAULT PCTFREE 10 INITRANS 1 MAXTRANS 255 
STORAGE( INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 )
NOPARALLEL
LOGGING 
NOCACHE 
NOMONITORING 
NOROWDEPENDENCIES
DISABLE ROW MOVEMENT 
/
CREATE INDEX PSFT.IND_STAT_TRANSHIST_AVG1
    ON PSFT.STAT_TRANSHIST_AVG(COLLECT_DATE, COUNTER)
TABLESPACE PSDEFAULT PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE( INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 )
NOPARALLEL
LOGGING 
/
CREATE INDEX PSFT.IND_STAT_TRANSHIST_AVG2
    ON PSFT.STAT_TRANSHIST_AVG(PM_CONTEXT_VALUE1, PM_CONTEXT_VALUE2, PM_CONTEXT_VALUE3, AVERAGE)
TABLESPACE PSDEFAULT PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE( INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 )
NOPARALLEL
LOGGING 
/
GRANT SELECT ON PSFT.STAT_TRANSHIST_AVG TO PPERF
/
##########################################################################
##    NEW VERSION OF TABLE 
##
CREATE TABLE PPERF.STAT_TRANSHIST_AVG1  ( 
	COLLECT_DATE     	DATE NULL,
	SYSTEM_NAME			VARCHAR2(60) NOT NULL,
	PM_TRANSACTION		VARCHAR2(1024) NOT NULL,
	AVERAGE          	NUMBER NULL,
	STD_DEV          	NUMBER NULL,
	MEDIAN				NUMBER,
	MEDIAN1				NUMBER,
	MEDIAN2				NUMBER,
	MEDIAN3				NUMBER,
	COUNTER          	NUMBER NULL,
	SYNCDTTM         	DATE NULL 
	)
TABLESPACE PPERF PCTFREE 10 INITRANS 1 MAXTRANS 255 
STORAGE( INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT )
NOPARALLEL
LOGGING 
NOCACHE 
NOMONITORING 
NOROWDEPENDENCIES
DISABLE ROW MOVEMENT 
/
CREATE INDEX PPERF.IND_STAT_TRANSHIST_AVG1_1
	ON PPERF.STAT_TRANSHIST_AVG1(COLLECT_DATE, COUNTER)
TABLESPACE PPERF NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE( INITIAL 65536 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT )
NOPARALLEL
LOGGING 
/
CREATE INDEX PPERF.IND_STAT_TRANSHIST_AVG1_2
	ON PPERF.STAT_TRANSHIST_AVG1(PM_TRANSACTION, AVERAGE)
TABLESPACE PPERF NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE( INITIAL 65536 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT )
NOPARALLEL
LOGGING 
/
GRANT SELECT, INSERT, UPDATE, DELETE ON PPERF.STAT_TRANSHIST_AVG1 TO PSFT
/
