#########################################################
## Create tables for the application
## Here are the base tables, more tables come with
## the rails deployment
##
## Create with user PPERF
##
## Table for import logging #############################
##
CREATE TABLE STATS_IMPORT_LOG  ( 
	DTTM   	DATE NULL,
	MESSAGE	VARCHAR2(200) NULL,
	ERROR  	VARCHAR2(100) NULL 
	)
TABLESPACE PPERF 
PCTFREE 10 INITRANS 1 MAXTRANS 255 
STORAGE( INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT )
NOPARALLEL
LOGGING 
NOCACHE 
NOMONITORING 
NOROWDEPENDENCIES
DISABLE ROW MOVEMENT 
;

## Table for import logging #############################
##
CREATE TABLE STAT_TRANSHIST_AVG  ( 
	COLLECT_DATE  	DATE NULL,
	SYSTEM_NAME   	VARCHAR2(60) NOT NULL,
	PM_TRANSACTION	VARCHAR2(1024) NOT NULL,
	AVERAGE       	NUMBER NULL,
	STD_DEV       	NUMBER NULL,
	MEDIAN        	NUMBER NULL,
	MEDIAN1       	NUMBER NULL,
	MEDIAN2       	NUMBER NULL,
	MEDIAN3       	NUMBER NULL,
	COUNTER       	NUMBER NULL,
	SYNCDTTM      	DATE NULL,
	MIN           	NUMBER NULL,
	MAX           	NUMBER NULL 
	)
TABLESPACE PPERF 
PCTFREE 10 INITRANS 1 MAXTRANS 255 
STORAGE( INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT )
NOPARALLEL
LOGGING 
NOCACHE 
NOMONITORING 
NOROWDEPENDENCIES
DISABLE ROW MOVEMENT 
;
CREATE UNIQUE INDEX IND_STAT_TRANSHIST_AVG1_1
	ON STAT_TRANSHIST_AVG(PM_TRANSACTION, COLLECT_DATE, SYSTEM_NAME)
TABLESPACE PPERF
NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE( INITIAL 65536 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT )
NOPARALLEL
LOGGING 
;
CREATE INDEX IND_STAT_TRANSHIST_AVG1_2
	ON STAT_TRANSHIST_AVG(PM_TRANSACTION, SYSTEM_NAME, AVERAGE)
TABLESPACE PPERF 
NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE( INITIAL 65536 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT )
NOPARALLEL
LOGGING 
;
CREATE INDEX IND_STAT_TRANSHIST_AVG1_3
	ON STAT_TRANSHIST_AVG(COLLECT_DATE, SYSTEM_NAME, COUNTER)
TABLESPACE PPERF 
NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE( INITIAL 65536 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT )
NOPARALLEL
LOGGING 
;


